# Generated by Django 5.0.4 on 2024-04-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookId',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='detail',
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
