# Generated by Django 5.0.4 on 2024-04-04 02:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_bookid_book_id_remove_book_detail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Customer',
        ),
    ]
