# Generated by Django 5.0.3 on 2024-04-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
