# Generated by Django 5.0.3 on 2024-04-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact_number',
        ),
    ]
