# Generated by Django 5.0.3 on 2024-05-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_order_is_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='address',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='barangay',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='region',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
