# Generated by Django 5.0.3 on 2024-05-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in progress', 'In Progress'), ('paid', 'Paid'), ('completed', 'Completed')], default='in progress', max_length=15),
        ),
    ]
