# Generated by Django 5.0.3 on 2024-05-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Paid', 'Paid'), ('Completed', 'Completed')], default='In Progress', max_length=15),
        ),
    ]
