# Generated by Django 5.0.3 on 2024-05-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in progress', 'In Progress'), ('paid', 'Paid'), ('completed', 'Completed')], default='In Progress', max_length=15),
        ),
    ]
