# Generated by Django 5.0.3 on 2024-05-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookImage',
        ),
    ]
